[package]
name = "server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = { version = "1.2.0", features = ["rand", "unstable"] }
log = "0.4"
anyhow = "1.0.98"
spacetimedsl = "0.10.0"

[lints.clippy]
too_many_arguments = "allow"
