// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::asteroid_type::Asteroid;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `asteroids`.
///
/// Obtain a handle from the [`AsteroidsTableAccess::asteroids`] method on [`super::RemoteTables`],
/// like `ctx.db.asteroids()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.asteroids().on_insert(...)`.
pub struct AsteroidsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Asteroid>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `asteroids`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AsteroidsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AsteroidsTableHandle`], which mediates access to the table `asteroids`.
    fn asteroids(&self) -> AsteroidsTableHandle<'_>;
}

impl AsteroidsTableAccess for super::RemoteTables {
    fn asteroids(&self) -> AsteroidsTableHandle<'_> {
        AsteroidsTableHandle {
            imp: self.imp.get_table::<Asteroid>("asteroids"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AsteroidsInsertCallbackId(__sdk::CallbackId);
pub struct AsteroidsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AsteroidsTableHandle<'ctx> {
    type Row = Asteroid;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Asteroid> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AsteroidsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AsteroidsInsertCallbackId {
        AsteroidsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AsteroidsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AsteroidsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AsteroidsDeleteCallbackId {
        AsteroidsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AsteroidsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Asteroid>("asteroids");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct AsteroidsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AsteroidsTableHandle<'ctx> {
    type UpdateCallbackId = AsteroidsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AsteroidsUpdateCallbackId {
        AsteroidsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AsteroidsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Asteroid>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Asteroid>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `asteroids`,
/// which allows point queries on the field of the same name
/// via the [`AsteroidsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.asteroids().id().find(...)`.
pub struct AsteroidsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Asteroid, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AsteroidsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `asteroids`.
    pub fn id(&self) -> AsteroidsIdUnique<'ctx> {
        AsteroidsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AsteroidsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Asteroid> {
        self.imp.find(col_val)
    }
}
