// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use super::player_location_type::PlayerLocation;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_location`.
///
/// Obtain a handle from the [`PlayerLocationTableAccess::player_location`] method on [`super::RemoteTables`],
/// like `ctx.db.player_location()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_location().on_insert(...)`.
pub struct PlayerLocationTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerLocation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_location`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerLocationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerLocationTableHandle`], which mediates access to the table `player_location`.
    fn player_location(&self) -> PlayerLocationTableHandle<'_>;
}

impl PlayerLocationTableAccess for super::RemoteTables {
    fn player_location(&self) -> PlayerLocationTableHandle<'_> {
        PlayerLocationTableHandle {
            imp: self.imp.get_table::<PlayerLocation>("player_location"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerLocationInsertCallbackId(__sdk::CallbackId);
pub struct PlayerLocationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayerLocationTableHandle<'ctx> {
    type Row = PlayerLocation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerLocation> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerLocationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerLocationInsertCallbackId {
        PlayerLocationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerLocationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerLocationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerLocationDeleteCallbackId {
        PlayerLocationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerLocationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerLocation>("player_location");
    _table.add_unique_constraint::<__sdk::Identity>("player_id", |row| &row.player_id);
}
pub struct PlayerLocationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerLocationTableHandle<'ctx> {
    type UpdateCallbackId = PlayerLocationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerLocationUpdateCallbackId {
        PlayerLocationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerLocationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PlayerLocation>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerLocation>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `player_id` unique index on the table `player_location`,
/// which allows point queries on the field of the same name
/// via the [`PlayerLocationPlayerIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_location().player_id().find(...)`.
pub struct PlayerLocationPlayerIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerLocation, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerLocationTableHandle<'ctx> {
    /// Get a handle on the `player_id` unique index on the table `player_location`.
    pub fn player_id(&self) -> PlayerLocationPlayerIdUnique<'ctx> {
        PlayerLocationPlayerIdUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("player_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerLocationPlayerIdUnique<'ctx> {
    /// Find the subscribed row whose `player_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<PlayerLocation> {
        self.imp.find(col_val)
    }
}
