// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlayerLeaveShipArgs {}

impl From<PlayerLeaveShipArgs> for super::Reducer {
    fn from(args: PlayerLeaveShipArgs) -> Self {
        Self::PlayerLeaveShip
    }
}

impl __sdk::InModule for PlayerLeaveShipArgs {
    type Module = super::RemoteModule;
}

pub struct PlayerLeaveShipCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `player_leave_ship`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait player_leave_ship {
    /// Request that the remote module invoke the reducer `player_leave_ship` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_player_leave_ship`] callbacks.
    fn player_leave_ship(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `player_leave_ship`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`PlayerLeaveShipCallbackId`] can be passed to [`Self::remove_on_player_leave_ship`]
    /// to cancel the callback.
    fn on_player_leave_ship(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> PlayerLeaveShipCallbackId;
    /// Cancel a callback previously registered by [`Self::on_player_leave_ship`],
    /// causing it not to run in the future.
    fn remove_on_player_leave_ship(&self, callback: PlayerLeaveShipCallbackId);
}

impl player_leave_ship for super::RemoteReducers {
    fn player_leave_ship(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("player_leave_ship", PlayerLeaveShipArgs {})
    }
    fn on_player_leave_ship(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> PlayerLeaveShipCallbackId {
        PlayerLeaveShipCallbackId(self.imp.on_reducer(
            "player_leave_ship",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::PlayerLeaveShip {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_player_leave_ship(&self, callback: PlayerLeaveShipCallbackId) {
        self.imp.remove_on_reducer("player_leave_ship", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `player_leave_ship`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_player_leave_ship {
    /// Set the call-reducer flags for the reducer `player_leave_ship` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn player_leave_ship(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_player_leave_ship for super::SetReducerFlags {
    fn player_leave_ship(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("player_leave_ship", flags);
    }
}
