// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlayerReadyArgs {}

impl From<PlayerReadyArgs> for super::Reducer {
    fn from(args: PlayerReadyArgs) -> Self {
        Self::PlayerReady
    }
}

impl __sdk::InModule for PlayerReadyArgs {
    type Module = super::RemoteModule;
}

pub struct PlayerReadyCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `player_ready`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait player_ready {
    /// Request that the remote module invoke the reducer `player_ready` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_player_ready`] callbacks.
    fn player_ready(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `player_ready`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`PlayerReadyCallbackId`] can be passed to [`Self::remove_on_player_ready`]
    /// to cancel the callback.
    fn on_player_ready(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> PlayerReadyCallbackId;
    /// Cancel a callback previously registered by [`Self::on_player_ready`],
    /// causing it not to run in the future.
    fn remove_on_player_ready(&self, callback: PlayerReadyCallbackId);
}

impl player_ready for super::RemoteReducers {
    fn player_ready(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("player_ready", PlayerReadyArgs {})
    }
    fn on_player_ready(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> PlayerReadyCallbackId {
        PlayerReadyCallbackId(self.imp.on_reducer(
            "player_ready",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::PlayerReady {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_player_ready(&self, callback: PlayerReadyCallbackId) {
        self.imp.remove_on_reducer("player_ready", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `player_ready`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_player_ready {
    /// Set the call-reducer flags for the reducer `player_ready` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn player_ready(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_player_ready for super::SetReducerFlags {
    fn player_ready(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("player_ready", flags);
    }
}
