// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlayerEnterShipArgs {
    pub ship_id: u64,
}

impl From<PlayerEnterShipArgs> for super::Reducer {
    fn from(args: PlayerEnterShipArgs) -> Self {
        Self::PlayerEnterShip {
            ship_id: args.ship_id,
        }
    }
}

impl __sdk::InModule for PlayerEnterShipArgs {
    type Module = super::RemoteModule;
}

pub struct PlayerEnterShipCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `player_enter_ship`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait player_enter_ship {
    /// Request that the remote module invoke the reducer `player_enter_ship` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_player_enter_ship`] callbacks.
    fn player_enter_ship(&self, ship_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `player_enter_ship`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`PlayerEnterShipCallbackId`] can be passed to [`Self::remove_on_player_enter_ship`]
    /// to cancel the callback.
    fn on_player_enter_ship(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> PlayerEnterShipCallbackId;
    /// Cancel a callback previously registered by [`Self::on_player_enter_ship`],
    /// causing it not to run in the future.
    fn remove_on_player_enter_ship(&self, callback: PlayerEnterShipCallbackId);
}

impl player_enter_ship for super::RemoteReducers {
    fn player_enter_ship(&self, ship_id: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("player_enter_ship", PlayerEnterShipArgs { ship_id })
    }
    fn on_player_enter_ship(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> PlayerEnterShipCallbackId {
        PlayerEnterShipCallbackId(self.imp.on_reducer(
            "player_enter_ship",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::PlayerEnterShip { ship_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, ship_id)
            }),
        ))
    }
    fn remove_on_player_enter_ship(&self, callback: PlayerEnterShipCallbackId) {
        self.imp.remove_on_reducer("player_enter_ship", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `player_enter_ship`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_player_enter_ship {
    /// Set the call-reducer flags for the reducer `player_enter_ship` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn player_enter_ship(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_player_enter_ship for super::SetReducerFlags {
    fn player_enter_ship(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("player_enter_ship", flags);
    }
}
