// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::ship_location_type::ShipLocation;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ship_locations`.
///
/// Obtain a handle from the [`ShipLocationsTableAccess::ship_locations`] method on [`super::RemoteTables`],
/// like `ctx.db.ship_locations()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_locations().on_insert(...)`.
pub struct ShipLocationsTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShipLocation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ship_locations`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipLocationsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipLocationsTableHandle`], which mediates access to the table `ship_locations`.
    fn ship_locations(&self) -> ShipLocationsTableHandle<'_>;
}

impl ShipLocationsTableAccess for super::RemoteTables {
    fn ship_locations(&self) -> ShipLocationsTableHandle<'_> {
        ShipLocationsTableHandle {
            imp: self.imp.get_table::<ShipLocation>("ship_locations"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipLocationsInsertCallbackId(__sdk::CallbackId);
pub struct ShipLocationsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipLocationsTableHandle<'ctx> {
    type Row = ShipLocation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShipLocation> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ShipLocationsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipLocationsInsertCallbackId {
        ShipLocationsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipLocationsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipLocationsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipLocationsDeleteCallbackId {
        ShipLocationsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipLocationsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ShipLocation>("ship_locations");
    _table.add_unique_constraint::<u64>("ship_id", |row| &row.ship_id);
}
pub struct ShipLocationsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipLocationsTableHandle<'ctx> {
    type UpdateCallbackId = ShipLocationsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipLocationsUpdateCallbackId {
        ShipLocationsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipLocationsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ShipLocation>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ShipLocation>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `ship_id` unique index on the table `ship_locations`,
/// which allows point queries on the field of the same name
/// via the [`ShipLocationsShipIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_locations().ship_id().find(...)`.
pub struct ShipLocationsShipIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ShipLocation, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShipLocationsTableHandle<'ctx> {
    /// Get a handle on the `ship_id` unique index on the table `ship_locations`.
    pub fn ship_id(&self) -> ShipLocationsShipIdUnique<'ctx> {
        ShipLocationsShipIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("ship_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShipLocationsShipIdUnique<'ctx> {
    /// Find the subscribed row whose `ship_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ShipLocation> {
        self.imp.find(col_val)
    }
}
