// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShipType {
    pub id: u64,
    pub name: String,
    pub camera_offset_x: f32,
    pub camera_offset_y: f32,
    pub camera_offset_z: f32,
    pub mass: f32,
    pub linear_damping: f32,
    pub angular_damping: f32,
    pub thrust: f32,
    pub vertical_thrust: f32,
    pub lateral_thrust: f32,
    pub pitch_torque: f32,
    pub yaw_torque: f32,
    pub roll_torque: f32,
}

impl __sdk::InModule for ShipType {
    type Module = super::RemoteModule;
}
