// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::ship_pilot_type::ShipPilot;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ship_pilots`.
///
/// Obtain a handle from the [`ShipPilotsTableAccess::ship_pilots`] method on [`super::RemoteTables`],
/// like `ctx.db.ship_pilots()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_pilots().on_insert(...)`.
pub struct ShipPilotsTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShipPilot>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ship_pilots`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipPilotsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipPilotsTableHandle`], which mediates access to the table `ship_pilots`.
    fn ship_pilots(&self) -> ShipPilotsTableHandle<'_>;
}

impl ShipPilotsTableAccess for super::RemoteTables {
    fn ship_pilots(&self) -> ShipPilotsTableHandle<'_> {
        ShipPilotsTableHandle {
            imp: self.imp.get_table::<ShipPilot>("ship_pilots"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipPilotsInsertCallbackId(__sdk::CallbackId);
pub struct ShipPilotsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipPilotsTableHandle<'ctx> {
    type Row = ShipPilot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShipPilot> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ShipPilotsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipPilotsInsertCallbackId {
        ShipPilotsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipPilotsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipPilotsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipPilotsDeleteCallbackId {
        ShipPilotsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipPilotsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ShipPilot>("ship_pilots");
    _table.add_unique_constraint::<u64>("ship_id", |row| &row.ship_id);
    _table.add_unique_constraint::<__sdk::Identity>("player_id", |row| &row.player_id);
}
pub struct ShipPilotsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipPilotsTableHandle<'ctx> {
    type UpdateCallbackId = ShipPilotsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipPilotsUpdateCallbackId {
        ShipPilotsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipPilotsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ShipPilot>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ShipPilot>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `ship_id` unique index on the table `ship_pilots`,
/// which allows point queries on the field of the same name
/// via the [`ShipPilotsShipIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_pilots().ship_id().find(...)`.
pub struct ShipPilotsShipIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ShipPilot, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShipPilotsTableHandle<'ctx> {
    /// Get a handle on the `ship_id` unique index on the table `ship_pilots`.
    pub fn ship_id(&self) -> ShipPilotsShipIdUnique<'ctx> {
        ShipPilotsShipIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("ship_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShipPilotsShipIdUnique<'ctx> {
    /// Find the subscribed row whose `ship_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ShipPilot> {
        self.imp.find(col_val)
    }
}

/// Access to the `player_id` unique index on the table `ship_pilots`,
/// which allows point queries on the field of the same name
/// via the [`ShipPilotsPlayerIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_pilots().player_id().find(...)`.
pub struct ShipPilotsPlayerIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ShipPilot, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShipPilotsTableHandle<'ctx> {
    /// Get a handle on the `player_id` unique index on the table `ship_pilots`.
    pub fn player_id(&self) -> ShipPilotsPlayerIdUnique<'ctx> {
        ShipPilotsPlayerIdUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("player_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShipPilotsPlayerIdUnique<'ctx> {
    /// Find the subscribed row whose `player_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<ShipPilot> {
        self.imp.find(col_val)
    }
}
