// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::ship_type_type::ShipType;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ship_types`.
///
/// Obtain a handle from the [`ShipTypesTableAccess::ship_types`] method on [`super::RemoteTables`],
/// like `ctx.db.ship_types()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_types().on_insert(...)`.
pub struct ShipTypesTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShipType>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ship_types`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipTypesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipTypesTableHandle`], which mediates access to the table `ship_types`.
    fn ship_types(&self) -> ShipTypesTableHandle<'_>;
}

impl ShipTypesTableAccess for super::RemoteTables {
    fn ship_types(&self) -> ShipTypesTableHandle<'_> {
        ShipTypesTableHandle {
            imp: self.imp.get_table::<ShipType>("ship_types"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipTypesInsertCallbackId(__sdk::CallbackId);
pub struct ShipTypesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipTypesTableHandle<'ctx> {
    type Row = ShipType;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShipType> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ShipTypesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipTypesInsertCallbackId {
        ShipTypesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipTypesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipTypesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipTypesDeleteCallbackId {
        ShipTypesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipTypesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ShipType>("ship_types");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct ShipTypesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipTypesTableHandle<'ctx> {
    type UpdateCallbackId = ShipTypesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipTypesUpdateCallbackId {
        ShipTypesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipTypesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ShipType>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ShipType>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `ship_types`,
/// which allows point queries on the field of the same name
/// via the [`ShipTypesIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_types().id().find(...)`.
pub struct ShipTypesIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ShipType, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShipTypesTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ship_types`.
    pub fn id(&self) -> ShipTypesIdUnique<'ctx> {
        ShipTypesIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShipTypesIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ShipType> {
        self.imp.find(col_val)
    }
}
