// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::ship_type::Ship;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ships`.
///
/// Obtain a handle from the [`ShipsTableAccess::ships`] method on [`super::RemoteTables`],
/// like `ctx.db.ships()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ships().on_insert(...)`.
pub struct ShipsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Ship>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ships`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipsTableHandle`], which mediates access to the table `ships`.
    fn ships(&self) -> ShipsTableHandle<'_>;
}

impl ShipsTableAccess for super::RemoteTables {
    fn ships(&self) -> ShipsTableHandle<'_> {
        ShipsTableHandle {
            imp: self.imp.get_table::<Ship>("ships"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipsInsertCallbackId(__sdk::CallbackId);
pub struct ShipsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipsTableHandle<'ctx> {
    type Row = Ship;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Ship> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ShipsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipsInsertCallbackId {
        ShipsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipsDeleteCallbackId {
        ShipsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Ship>("ships");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct ShipsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipsTableHandle<'ctx> {
    type UpdateCallbackId = ShipsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipsUpdateCallbackId {
        ShipsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Ship>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Ship>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `ships`,
/// which allows point queries on the field of the same name
/// via the [`ShipsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ships().id().find(...)`.
pub struct ShipsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Ship, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShipsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ships`.
    pub fn id(&self) -> ShipsIdUnique<'ctx> {
        ShipsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShipsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Ship> {
        self.imp.find(col_val)
    }
}
