// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use super::station_type::Station;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `station`.
///
/// Obtain a handle from the [`StationTableAccess::station`] method on [`super::RemoteTables`],
/// like `ctx.db.station()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.station().on_insert(...)`.
pub struct StationTableHandle<'ctx> {
    imp: __sdk::TableHandle<Station>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `station`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StationTableHandle`], which mediates access to the table `station`.
    fn station(&self) -> StationTableHandle<'_>;
}

impl StationTableAccess for super::RemoteTables {
    fn station(&self) -> StationTableHandle<'_> {
        StationTableHandle {
            imp: self.imp.get_table::<Station>("station"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StationInsertCallbackId(__sdk::CallbackId);
pub struct StationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StationTableHandle<'ctx> {
    type Row = Station;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Station> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StationInsertCallbackId {
        StationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StationDeleteCallbackId {
        StationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Station>("station");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct StationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StationTableHandle<'ctx> {
    type UpdateCallbackId = StationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StationUpdateCallbackId {
        StationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Station>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Station>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `station`,
/// which allows point queries on the field of the same name
/// via the [`StationIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.station().id().find(...)`.
pub struct StationIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Station, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StationTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `station`.
    pub fn id(&self) -> StationIdUnique<'ctx> {
        StationIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StationIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Station> {
        self.imp.find(col_val)
    }
}
