// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use super::station_rotation_update_type::StationRotationUpdate;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `station_rotation_update`.
///
/// Obtain a handle from the [`StationRotationUpdateTableAccess::station_rotation_update`] method on [`super::RemoteTables`],
/// like `ctx.db.station_rotation_update()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.station_rotation_update().on_insert(...)`.
pub struct StationRotationUpdateTableHandle<'ctx> {
    imp: __sdk::TableHandle<StationRotationUpdate>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `station_rotation_update`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StationRotationUpdateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StationRotationUpdateTableHandle`], which mediates access to the table `station_rotation_update`.
    fn station_rotation_update(&self) -> StationRotationUpdateTableHandle<'_>;
}

impl StationRotationUpdateTableAccess for super::RemoteTables {
    fn station_rotation_update(&self) -> StationRotationUpdateTableHandle<'_> {
        StationRotationUpdateTableHandle {
            imp: self
                .imp
                .get_table::<StationRotationUpdate>("station_rotation_update"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StationRotationUpdateInsertCallbackId(__sdk::CallbackId);
pub struct StationRotationUpdateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StationRotationUpdateTableHandle<'ctx> {
    type Row = StationRotationUpdate;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StationRotationUpdate> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StationRotationUpdateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StationRotationUpdateInsertCallbackId {
        StationRotationUpdateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StationRotationUpdateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StationRotationUpdateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StationRotationUpdateDeleteCallbackId {
        StationRotationUpdateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StationRotationUpdateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StationRotationUpdate>("station_rotation_update");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct StationRotationUpdateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StationRotationUpdateTableHandle<'ctx> {
    type UpdateCallbackId = StationRotationUpdateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StationRotationUpdateUpdateCallbackId {
        StationRotationUpdateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StationRotationUpdateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<StationRotationUpdate>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StationRotationUpdate>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `station_rotation_update`,
/// which allows point queries on the field of the same name
/// via the [`StationRotationUpdateScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.station_rotation_update().scheduled_id().find(...)`.
pub struct StationRotationUpdateScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StationRotationUpdate, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StationRotationUpdateTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `station_rotation_update`.
    pub fn scheduled_id(&self) -> StationRotationUpdateScheduledIdUnique<'ctx> {
        StationRotationUpdateScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StationRotationUpdateScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<StationRotationUpdate> {
        self.imp.find(col_val)
    }
}
