// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::station_type::Station;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `stations`.
///
/// Obtain a handle from the [`StationsTableAccess::stations`] method on [`super::RemoteTables`],
/// like `ctx.db.stations()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.stations().on_insert(...)`.
pub struct StationsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Station>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `stations`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StationsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StationsTableHandle`], which mediates access to the table `stations`.
    fn stations(&self) -> StationsTableHandle<'_>;
}

impl StationsTableAccess for super::RemoteTables {
    fn stations(&self) -> StationsTableHandle<'_> {
        StationsTableHandle {
            imp: self.imp.get_table::<Station>("stations"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StationsInsertCallbackId(__sdk::CallbackId);
pub struct StationsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StationsTableHandle<'ctx> {
    type Row = Station;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Station> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StationsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StationsInsertCallbackId {
        StationsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StationsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StationsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StationsDeleteCallbackId {
        StationsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StationsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Station>("stations");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct StationsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StationsTableHandle<'ctx> {
    type UpdateCallbackId = StationsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StationsUpdateCallbackId {
        StationsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StationsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Station>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Station>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `stations`,
/// which allows point queries on the field of the same name
/// via the [`StationsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.stations().id().find(...)`.
pub struct StationsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Station, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StationsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `stations`.
    pub fn id(&self) -> StationsIdUnique<'ctx> {
        StationsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StationsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Station> {
        self.imp.find(col_val)
    }
}
