// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TmpArgs {}

impl From<TmpArgs> for super::Reducer {
    fn from(args: TmpArgs) -> Self {
        Self::Tmp
    }
}

impl __sdk::InModule for TmpArgs {
    type Module = super::RemoteModule;
}

pub struct TmpCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `tmp`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait tmp {
    /// Request that the remote module invoke the reducer `tmp` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_tmp`] callbacks.
    fn tmp(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `tmp`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`TmpCallbackId`] can be passed to [`Self::remove_on_tmp`]
    /// to cancel the callback.
    fn on_tmp(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> TmpCallbackId;
    /// Cancel a callback previously registered by [`Self::on_tmp`],
    /// causing it not to run in the future.
    fn remove_on_tmp(&self, callback: TmpCallbackId);
}

impl tmp for super::RemoteReducers {
    fn tmp(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("tmp", TmpArgs {})
    }
    fn on_tmp(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> TmpCallbackId {
        TmpCallbackId(self.imp.on_reducer(
            "tmp",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::Tmp {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_tmp(&self, callback: TmpCallbackId) {
        self.imp.remove_on_reducer("tmp", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `tmp`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_tmp {
    /// Set the call-reducer flags for the reducer `tmp` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn tmp(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_tmp for super::SetReducerFlags {
    fn tmp(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("tmp", flags);
    }
}
