// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::station_rotation_update_type::StationRotationUpdate;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct WorldUpdateStationsRotationArgs {
    pub update: StationRotationUpdate,
}

impl From<WorldUpdateStationsRotationArgs> for super::Reducer {
    fn from(args: WorldUpdateStationsRotationArgs) -> Self {
        Self::WorldUpdateStationsRotation {
            update: args.update,
        }
    }
}

impl __sdk::InModule for WorldUpdateStationsRotationArgs {
    type Module = super::RemoteModule;
}

pub struct WorldUpdateStationsRotationCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `world_update_stations_rotation`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait world_update_stations_rotation {
    /// Request that the remote module invoke the reducer `world_update_stations_rotation` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_world_update_stations_rotation`] callbacks.
    fn world_update_stations_rotation(&self, update: StationRotationUpdate) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `world_update_stations_rotation`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`WorldUpdateStationsRotationCallbackId`] can be passed to [`Self::remove_on_world_update_stations_rotation`]
    /// to cancel the callback.
    fn on_world_update_stations_rotation(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &StationRotationUpdate) + Send + 'static,
    ) -> WorldUpdateStationsRotationCallbackId;
    /// Cancel a callback previously registered by [`Self::on_world_update_stations_rotation`],
    /// causing it not to run in the future.
    fn remove_on_world_update_stations_rotation(
        &self,
        callback: WorldUpdateStationsRotationCallbackId,
    );
}

impl world_update_stations_rotation for super::RemoteReducers {
    fn world_update_stations_rotation(&self, update: StationRotationUpdate) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "world_update_stations_rotation",
            WorldUpdateStationsRotationArgs { update },
        )
    }
    fn on_world_update_stations_rotation(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &StationRotationUpdate) + Send + 'static,
    ) -> WorldUpdateStationsRotationCallbackId {
        WorldUpdateStationsRotationCallbackId(self.imp.on_reducer(
            "world_update_stations_rotation",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::WorldUpdateStationsRotation { update },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, update)
            }),
        ))
    }
    fn remove_on_world_update_stations_rotation(
        &self,
        callback: WorldUpdateStationsRotationCallbackId,
    ) {
        self.imp
            .remove_on_reducer("world_update_stations_rotation", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `world_update_stations_rotation`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_world_update_stations_rotation {
    /// Set the call-reducer flags for the reducer `world_update_stations_rotation` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn world_update_stations_rotation(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_world_update_stations_rotation for super::SetReducerFlags {
    fn world_update_stations_rotation(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("world_update_stations_rotation", flags);
    }
}
